version: '3'
services:
  web:
    image: node
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
    environment:
      SEQ_USER: postgres
      SEQ_PW: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/tmaapp_dev
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
